### ISSUE TITLE
프로그램 아직도 작동하나요 + 열리지 않습니다

### ISSUE THREAD

**Issue by enarkay** [jikjky/TwipControlKeyboard#1]
프로그램을 다운받은 후 TCK.exe 를 열어보려 하였으나 프로그램이 실행되지 않습니다.
혹시나 제 컴퓨터 / 백신 / 방화벽 등의 문제인가 싶어 모두 확인해보고 심지어 다른 사람에게도 받아서 열어보라고 시켜보았는데, 마찬가지로 프로그램이 실행되지 않는다고 하네요.

**Comment by jikjky** [comment]
https://chromedriver.chromium.org/downloads
여기서 자신의 크롬 버전에 맞는? 최신 버전의?
chromedriver를 다운받은후
chromedriver.exe를 교체하시고 실행해 보세요.
교체후 실행되는것은 확인했습니다.
다른 기능들이 정상적으로 동작하는지는 확인을 못했네요

일단 배포파일에 제가 동작하는 Driver랑 최신빌드 적용해서 다시 올렸으니 배포파일 다시 다운받고 해보세요

**Comment by enarkay** [comment]
@jikjky 감사합니다, 저도 아직 기능을 테스트 해보지는 못했지만 말씀해주신대로 최신 크롬 버전에 맞는 chromedrive를 받아서 실행한 후 프로그램을 실행해보니 정상 작동하네요. 그런데 여전히 질문이 있는데

chromedriver 는 한 번만 실행하면 그 다음부터는 꺼둬도 되는 일회성 드라이버 설치의 개념인가요, 아니면 프로그램이 작동하기 위해서는 매 번 실행시킨 상태로 띄워둬야 하는 반복성 사전 실행 프로그램의 개념인가요?

**Comment by jikjky** [comment]
@enarkay 한번만 설치하면 Chrome의 버전이 달라지지않으면 사용할수 있는걸로 알고 있습니다

[Download](https://github.com/jikjky/TwipControlKeyboard/raw/master/TCK_WebSocket.zip)

원래 셀러리움을 사용해서 프로그램을 사용했는데 WebSocket을 사용하여 동작하도록 마지막으로 바꾸고 배포파일을 수정하지 않았네요

그래서 위 버전은 chromedriver를 사용하지 않네요

테스트 해볼려고 하니 바이러스 프로그램이다 뭐다 라고 떠서 확인을 할수가 없네요

**Comment by enarkay** [comment]
@jikjky 친절한 답변 감사합니다~! 나중에 실질적으로 프로그램 사용/테스트 중 또 문제가 생기거나 추가로 여쭤볼 사항이 생기면 말씀드리겠습니다. 평온하고 즐거운 한 주 되시기 바랍니다 :)

**Comment by enarkay** [comment]
@jikjky 제가 예상한 바로는 실제 후원이 아니라 트윕/투네 대시보드에서 후원 테스트를 통해서도 프로그램 동작 여부를 확인할 수 있을 걸로 생각했는데, 혹시 후원 테스트로는 동작하지 않고 실제 후원으로만 반응하는 식인가요??

일단 후원 테스트로는 1000원 후원 금액에 맞춰서 여러가지를 테스트 해보았는데 어떤 것도 작동하지 않는 것 같네요

**Comment by jikjky** [comment]
@enarkay

[Download](https://github.com/jikjky/TwipControlKeyboard/raw/master/TCK_WebSocket.zip)

이걸로 다시 다운받으시고 해보세요

후원 테스트로도 되는거 확인했습니다

![Imgur](https://i.imgur.com/HylxJg5.png)

**Comment by enarkay** [comment]
@jikjky 감사합니다, 위 올려주신 파일로는 정상적으로 잘 작동하는 것 확인하였습니다.
다만 이 역시 제가 무언가 잘못하고 있는지, 아니면 프로그램의 버그인지, 아래와 같은 문제를 발견하였습니다.

예를 들어 Time을 8초(8000)로 설정하였을때, NoneClick의 경우 정상적으로 8초간 해당 키를 누르지 못하였으나
Click의 경우는 지정된 키를 8초간 누르고 있는 게 아니라, 그냥 한 번만 누르고 말았습니다.

예를 들어 w키를 지정했다면 제가 예상한 결과는 8초간 wwwwwwwww가 반복적으로 눌리고 있는 걸 예상하였으나,
실제 메모장에 입력된 것은 w 한 번으로 끝이었습니다.

아래 테스트 중 설정한 예시 설정값을 첨부합니다.
![image](https://github.com/jikjky/TwipControlKeyboard/assets/7910166/b59d9c10-7bff-4d4f-a5aa-5ee60effc193)

**Comment by jikjky** [comment]
@enarkay
Click은 한번밖에 안되게 되있고
그 시간동안 꾹 누르고 있는건 맞을텐데 입력은 한번밖에 안되더라고요

여러번 누를려면
w delay 100
w delay 200
w delay 300
w delay 400
이런식으로 여러개 만드는 방법밖에 없을거 같네요

**Comment by enarkay** [comment]
@jikjky 안 그래도 그 방법을 생각 해보지 않은 건 아닌데, 그 경우에도 사실 '연타'에 해당하지 꾹 누르고 있는 입력과는 다를테니 시도해보지 않았습니다ㅜ

예를 들어 강제로 8초간 앞으로 이동하게끔 시키고 싶다고 했을때, 이걸 위해서 찔끔 찔끔 연타가 아닌 자연스럽게 앞으로 죽~ 이동하는 입력을 구현하기 위해 대체 얼마나 많은 이벤트를 추가해야 할 지 막막하기도 하구요;;

그래서 이 시점에서 여쭤보고 싶은 사항이 두 가지 있는데
1) 혹시 위 묘사된 부분 수정하여 반영해주실 수 있으신지
2) 만약 수정할 시간 내지는 업데이트 의사가 없다고 하신다면, 본 프로그램을 참고삼아 추가적인 기능을 넣거나 수정할 수 있도록 다른 개발자에게 커미션을 맡겨도 괜찮으신지
여쭤보고 싶습니다.

**Comment by jikjky** [comment]
@enarkay
입력은 한번 되는데 꾹 누르고 있는게 맞거든요?
아마 원하는대로 될거에요

프로그램은 마음대로 수정하시고 사용하셔도 됩니다

**Comment by enarkay** [comment]
@jikjky 앗 그러네요! 메모장으로 테스트 했을때는 한 번만 입력되는 걸로 인식하는데, 말씀 듣고서 아무 게임이나 하나 골라잡아서 해보니 정말 죽 누르고 있는 걸로 인식되네요!

항상 친절한 안내와 답변 너무 너무 감사드립니다 :)
